### ISSUE TITLE
Windows location log.txt

### ISSUE THREAD

**Issue by rdeveen** [mre/teams-call#2]
I think the file on Windows 10 is here:
`%AppData%\Microsoft\Teams\logs.txt`

**Comment by mre** [comment]
Thanks @rdeveen. Opened a PR for that. I cannot test this locally as I don't have a Windows machine, but maybe you could have a look if it makes sense. Also, does bash work the same on Windows?

**Comment by rdeveen** [comment]
You can run BASH script on Windows 10 if you have WSL but the %AppData% does not give the correct path. Running BASH on Windows is not the preferred way for this. I found a PowerShell script that is doing the same. For Windows users check this one: https://github.com/EBOOZ/TeamsStatus

**Comment by mre** [comment]
Ah makes sense. I added a note to the docs and to the script itself. Thanks for investigating.
